cors:
  originPatterns: http://localhost:8080
file:
  upload-dir: /Users/Andrt/OneDrive/Área de Trabalho/CURSOS/UDEMY/REST API Spring Boot Java Docker/Secao_21_Upload_Download_Arquivos
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useLegacyDatetimeCode=false&serverTimezone=GMT%2B3
    username: root
    password: 220624And
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
    show_sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true